import exercises from '../../assets/workoutData.json';

function useData({exType,bPart}) {
    let result = exercises.filter((exercise)=>exercise.exType === exType && exercise.bPart === bPart)
    const bodyParts = {
        'chest' : "The chest includes some of the largest muscles in the upper body and you use the chest muscles all day long. For example, the chest muscles are needed to push open a door, wash your hair, or get up and down from the floor. It's important to keep these muscles strong for all your daily activities.  Your chest muscles are big and can handle more weight, which allows you to burn more calories when you exercise them. In fact, when you work your chest, your shoulders and arms are also involved, allowing you to exercise more of your body at once. A chest workout also serves as a great warmup for those smaller muscle groups.",
        'traps' : "You might be thinking that you should sink all of your muscle-building efforts into your chest, shoulders, and arms. That's not totally off the mark—but your back needs attention, too, for more than just symmetry's sake. One muscle you should give particular focus is the traps (a.k.a. the trapezius or trapezoid muscles). The long, quadrilateral-shaped muscle, which is composed of three parts (superior, middle, and inferior), takes up a ton of real estate on your upper back.The functions of the traps make it especially worth your focus. The muscle is big on its own, and you'll add size to your back and shoulders when you take on traps-focused movements—but your other upper body muscles will also benefit from strong traps.",
        'shoulders' : "Shoulder training requires so much subtlety. It's easy to overtrain your shoulders, because even when you're not expressly targeting them, they're still getting plenty of work. you need to be smart with your shoulder exercises, programming careful, smart moves instead of over-developing your delts with one or two exercises on repeat in every session. Shoulder workouts require caution, and really, you can isolate your shoulders with less frequency than many of your larger muscle groups.",
        'biceps' : "Your biceps are, essentially, the large muscle group that sits on the front section of your upper arm. You know the one we’re talking about. You stare at it often enough when flexing. It Latin, it’s known as the biceps brachii, which means two-headed muscle of the arm. And why’s that, well, your biceps are split into two sections: the long head and the short head.One of the main reasons people's biceps don't grows as big (or as quick) as they would like them to, is that they fail to recognise that the bicep is actually broken down into more than one part. Most guys tend to only focus on the brachii. But if you want thicker, fuller looking arms, you need to work all areas of the bicep.",
        'forearms' : "You train your biceps and you blast your triceps and you now to get in serious back and chest and leg work too. But how often are you training your forearms? How often do you give them extra gym attention?Because they just might be the key to unlocking greater strength and muscle and dominating all those other parts of your training too. Very often, forearm and grip training is underestimated, but the stronger you get your forearms and grip, the better you'll perform on exercises like pullups and rowss, and the less you'll have to think about grip on exercises like deadlifts.",
        'upper-abs' : "Abs, you see, are much more than a chiseled torso and an excuse to wear a tight t-shirt, they are also one of the most important muscles in your body and having a stronger core will help your strength in other lifts — helping your numbers on bench presses, overhead work, deadlifts and squats creep upwards and improve your recovery — while helping you maintain good posture and even eliminate back pain.Therefore, safe to say that ab exercises deserve as much time and attention as any other muscle group in your body, so it's important to do the right exercises.",
        'lower-abs' : "Abs, you see, are much more than a chiseled torso and an excuse to wear a tight t-shirt, they are also one of the most important muscles in your body and having a stronger core will help your strength in other lifts — helping your numbers on bench presses, overhead work, deadlifts and squats creep upwards and improve your recovery — while helping you maintain good posture and even eliminate back pain.Therefore, safe to say that ab exercises deserve as much time and attention as any other muscle group in your body, so it's important to do the right exercises.",
        'oblique' : "Your obliques are the muscles that many consider their 'side abs,' and technically, they're not wrong. But there's more to those two pairs of muscles—the external and internal obliques—that run along the sides of your core. The obliques work together to help you to bend side-to-side, rotate your torso from left to right, and assist with spinal flexion (the movement you'd typically associate with movements like crunches and situps that target those six-pack muscles). The obliques also actively resist against rotation to help stabilize and protect your spine.",
        'quads' : "The quads, or quadriceps, are the large, powerful muscles in the front and outsides of your thigh, just above the knee. A group of four muscles (hence the “quad” part), they’re largely responsible for straightening (or extending) your knee. They’re also responsible for the bulky, muscled look that some guys have in jeans and shorts.Not that this is all about vanity, because a dominant set of quads does more than complete a badass physique. Your quads are the key muscle group that straightens (or extends) your knee. That means they play a critical role in helping you stand up from a chair or drive upwards from a squat. And while your glutes and hamstrings are generally considered the engine for your power as a sprinter or leaper, your quads also play a role there, too.",
        'calves' : "To some extent, you’re always training your calves when you train legs. When you look at your most popular leg moves (squats, lunges, deadlifts) it’s important to understand that they work from the ground up. In the same way you need your forearms to grip implements when you train pulling and pressing motions, you need assistance from your calves to create the base for your lower-body moves.The calf muscles have three main parts. The largest and outermost muscle is the gastrocnemius. When you think of the calves, this is the baseball-sized muscle. There are two heads to the muscle, the lateral head which sits on the outside of the lower leg and the medial head that sits on the inside of the leg. The two heads can both work together. The gastrocnemius oversees the pointing of your toes. Easy rule: When the heel is above the toes, and your muscle is being flexed, that’s the gastroc.",
        // middle_back = "You might be thinking that you should sink all of your muscle-building efforts into your chest, shoulders, and arms. That's not totally off the mark—but your back needs attention, too, for more than just symmetry's sake. One muscle you should give particular focus is the traps (a.k.a. the trapezius or trapezoid muscles). The long, quadrilateral-shaped muscle, which is composed of three parts (superior, middle, and inferior), takes up a ton of real estate on your upper back.The functions of the traps make it especially worth your focus. The muscle is big on its own, and you'll add size to your back and shoulders when you take on traps-focused movements—but your other upper body muscles will also benefit from strong traps.",
        'middle-back' : "Your back muscles can play a bigger role than you might expect in assisting big-time compound movements that pay off in spades, like the bench press. Your upper- and mid-back muscles help to stabilize your shoulder joints, and the stronger and more stable your shoulders, the more weight you can lift in just about every upper-body exercise. Your hands have to be involved in back-focused exercises to handle the load, too, so don't be surprised when all those rowss result in bigger arm muscles.",
        'lower-back' : "Your back muscles can play a bigger role than you might expect in assisting big-time compound movements that pay off in spades, like the bench press. Your upper- and mid-back muscles help to stabilize your shoulder joints, and the stronger and more stable your shoulders, the more weight you can lift in just about every upper-body exercise. Your hands have to be involved in back-focused exercises to handle the load, too, so don't be surprised when all those rowss result in bigger arm muscles.",
        'lats' : "In order to work your lats you have to understand them at least a little: They’re the large, triangle-shaped muscles on the back, creating a thick taper from shoulder to waist. The muscle inserts into the upper part of the humerus, your upper arm bone, from the inside. Their purpose is main two-fold: Your lats primarily work when you pull things, and when you adduct things. What’s adduction? Raise your arms out to your sides, forming a “T” with your torso. Now lower them forcefully back to your sides. That forceful lowering action is adduction.",
        'triceps' : "Think of your triceps as the three-headed monster that will make your arms pop. The muscle takes its name from those three heads—the long head, the medial head, and the lateral head—and is essential for elbow extension. That means just about any time you're straightening your arms, whether you're pressing or doing extensions, your triceps are going to be involved. All three heads connect to your elbow and humerus (your upper arm bone), while long head alone connects to your shoulder blade, which makes the muscle involved in overhead pressing movements.",
        'glutes' : "No matter what sport or day-to-day activity you’re doing, good glute strength is crucial for endurance, power, and pain prevention,Your butt consists of three distinct muscles—the gluteus maximus, gluteus medius, and gluteus minimus—that attach your torso to your legs along a number of points, including the sacrum, pelvis, and femur.Whether you’re lifting, jumping, sprinting, or shooting a basketball, your glutes are key to tapping into that explosive push-off strength that comes from extending your hips.",
        'hamstrings' : "Do you want to run faster and jump higher? Do you want to squat and lunge more weight? And do you want to fill out a pair of shorts or swim trunks with meaty, muscular legs?Then you want to make sure to train your hamstrings—and spend at least some time every week doing dedicated, focused hamstring training. Very often, when most guys think of building strong, powerful legs, they imagine the quads, and the “teardrop” shaped muscles above the front of your knees are the focus and pursuit of plenty of bodybuilders."
    }
  return (
    {exercises:result,description: bodyParts[bPart]}
  )
}

export default useData